src_db:
  user: root
  password: 123456
  host: 172.16.0.99
  port: 3306
  db_name: schema_diff_1
dst_db:
  user: root
  password: 123456
  host: 172.16.0.99
  port: 3306
  db_name: schema_diff_2
diff_conf:
  ignore_character: false
  ignore_auto_increment: false
